Implement ShutdownHandle for ServiceProcessor
Cargill/splinter pull request #1196
Opened 2021-02-18 17:58 UTC by peterschwarz

This change implements the new ShutdownHandle crate for the ServiceProcessor, replacing its previous combination of handle and JoinHandles, when the "shutdown" feature is enabled.

Likewise it makes several changes to the daemon code to handle this experimental feature:

- Removes the need to send handles to the ctrl-c handler
- Removes the separate threads used to startup both the admin and health service processors
- Reworks the health service feature to include the requirement on the "shutdown" feature, as both are experimental.

2021-02-18 18:18 UTC, ltseeley submitted a review, later dismissed

2021-02-25 16:58 UTC, agunde406 requested changes

2021-02-25 16:58 UTC, agunde406 commented on libsplinter/src/service/mod.rs
> +#[cfg(not(feature = "shutdown"))]
typo in commit message splitnerd -> splinterd

2021-02-25 16:58 UTC, agunde406 commented on libsplinter/src/service/processor/mod.rs
>  /// Includes the service senders and join_handles for the service threads.
typo in commit message: shudown -> shutdown

2021-02-25 17:04 UTC, vaporos requested changes

2021-02-25 19:33 UTC, vaporos approved these changes

2021-02-25 19:41 UTC, agunde406 approved these changes

2021-02-25 22:18 UTC, merged