Update circuit integration tests
Cargill/splinter pull request #1245
Opened 2021-03-15 20:24 UTC by shannynalayna

This PR updates the circuit integration tests in the following ways:
- Updates how the tests wait for the change to be committed. Now, all nodes are checked before moving out of the loop to ensure all nodes are on the same page before moving on. Previously, only the nodes that hadn't submitted the payload would be checked in the wait loop. This resulted in issues where that submitter node's state wasn't up-to-date and the test would continue on, assuming it was without validating.
- Updates the happy path circuit create and circuit disband tests to include validation that a duplicate proposal will be rejected. This allows us to validate the case that duplicate proposals are rejected without running separate tests for these cases. 
- Also updates the comments for these tests to account for these updates

2021-03-16 17:22 UTC, isabeltomb requested changes

2021-03-16 17:22 UTC, isabeltomb commented on splinterd/tests/admin/circuit_lifecycle.rs
> +            .expect("Unable to list pro")
End of message missing

2021-03-16 17:22 UTC, isabeltomb commented on splinterd/tests/admin/circuit_lifecycle.rs
>  /// 6. Wait until the circuit is no longer available as an active circuit on the first node,
Numbering is off

2021-03-16 18:35 UTC, shannynalayna commented on splinterd/tests/admin/circuit_lifecycle.rs
> +            .expect("Unable to list pro")
Updated the error message here

2021-03-16 18:35 UTC, shannynalayna commented on splinterd/tests/admin/circuit_lifecycle.rs
>  /// 6. Wait until the circuit is no longer available as an active circuit on the first node,
Updated the numbering here

2021-03-16 19:23 UTC, isabeltomb approved these changes

2021-03-17 13:59 UTC, isabeltomb approved these changes

2021-03-17 14:04 UTC, agunde406 approved these changes

2021-03-17 16:11 UTC, merged