Add external registries to testing framework
Cargill/splinter pull request #1261
Opened 2021-03-19 23:03 UTC by isabeltomb

Add the ability to add a yaml file as an external registry to the testing framework. If any external registries are added a unified registry is created for the network with the internal registry and external read-only registries.

A yaml registry file can be added by passing the registry file names in a vector to the `with_external_registries` method when creating a new Network.

Example:
```
let network = Network::new()
        .with_default_rest_api_variant(RestApiVariant::ActixWeb1)
        .with_external_registries(vec![<file names in the format "file://file-path">])
        .add_nodes_with_defaults(1)
```

2021-03-23 18:09 UTC, peterschwarz requested changes

2021-03-23 18:09 UTC, peterschwarz commented on splinterd/src/node/runnable/admin.rs
> +                .filter_map(|registry| {
I’m not sure `filter_map` is the right way to go here. We should probably propagate the errors that can occur on the individual registries. 

Better to `map` and then `collect::<Result<Vec<_>, _>>()?`

2021-03-23 22:12 UTC, peterschwarz approved these changes

2021-03-29 13:47 UTC, agunde406 approved these changes

2021-03-30 15:35 UTC, merged