Update example config
Cargill/splinter pull request #1397
Opened 2021-06-17 15:16 UTC by rbuysse

2021-06-17 17:51 UTC, vaporos requested changes

2021-06-17 17:51 UTC, vaporos commented on splinterd/packaging/splinterd.toml.example
> +#version = "1"
This line (only this line) should be left uncommented since its metadata about the format of the file.

2021-06-17 17:51 UTC, vaporos commented on splinterd/packaging/splinterd.toml.example
> +#node_id = ""
Should we add a note that this must match the value in the file in /var/lib/splinter?

2021-06-22 21:01 UTC, vaporos approved these changes

2021-06-23 15:22 UTC, peterschwarz approved these changes

2021-06-23 17:46 UTC, merged