Fix scabbard batch result send/receive bug
Cargill/splinter pull request #1439
Opened 2021-07-16 21:16 UTC by isabeltomb

Update batch result receiving process to loop until getting a `None` result from the scheduler before shutting down. This change ensures the batch result is received.

Previously, when submitting transactions to scabbard, the error: "Unable to send batch result; receiver must have dropped" would occur randomly and somewhat frequently. This change fixes the issue by waiting for the scheduler to indicate it is finished by sending `None` before shutting down.

2021-07-16 21:38 UTC, peterschwarz submitted a review, later dismissed

2021-07-19 13:26 UTC, agunde406 requested changes

2021-07-19 13:26 UTC, agunde406 commented on services/scabbard/libscabbard/src/service/state.rs
> +        // after recieving the batch result wait until the receiver gets a `None` response
recieving -> receiving

2021-07-19 13:30 UTC, isabeltomb commented on services/scabbard/libscabbard/src/service/state.rs
> +        // after recieving the batch result wait until the receiver gets a `None` response
Fixed

2021-07-19 13:33 UTC, agunde406 approved these changes

2021-07-19 13:42 UTC, peterschwarz approved these changes

2021-07-19 21:08 UTC, merged