Node id block startup if file exists
Cargill/splinter pull request #1449
Opened 2021-07-29 17:40 UTC by Caleb-Hill

As node_id moves into the database eventually we want splinterd not to start with the old node_id storage file in place. This makes splinterd check for the file and exit with an error message if it exists.

2021-08-09 16:47 UTC, peterschwarz requested changes
Tested.  Works as expected when upgrading from the yaml file to a DB stored node-id. However, it does not have the existing behaviour of starting up and generating a node id if one is missing and not provided on the command line.

2021-08-09 19:21 UTC, peterschwarz approved these changes
Tested

2021-08-09 19:27 UTC, peterschwarz approved these changes

2021-08-09 20:51 UTC, isabeltomb reviewed
Tested

2021-08-09 20:51 UTC, isabeltomb commented on splinterd/src/main.rs
> +            // Check if the config obejct has a node_id, otherwise generate a random one.
s/obejct/object

2021-08-09 20:51 UTC, isabeltomb commented on splinterd/src/main.rs
> +                    .map_err(|err| UserError::from(InternalError::from_source(Box::new(err))))
I think "node-file-block" needs to be added to the feature guard for `use splinter::error::InternalError;` on line 44, attempting to compile with just the `node-file-block` feature returns the error: "failed to resolve: use of undeclared type `InternalError`"

2021-08-10 13:17 UTC, isabeltomb approved these changes

2021-08-10 13:38 UTC, peterschwarz approved these changes

2021-08-10 13:38 UTC, merged