Node file block clean up
Cargill/splinter pull request #1521
Opened 2021-09-20 15:18 UTC by Caleb-Hill

2021-09-27 18:20 UTC, agunde406 requested changes

2021-09-27 18:20 UTC, agunde406 commented on splinterd/src/node_id.rs
> +use rand::Rng;
Missing copyright

2021-09-27 18:20 UTC, agunde406 commented on splinterd/src/daemon.rs
> +        let node_id: String = crate::node_id::get_node_id(
Add a use statement above for get_node_id instead of useing the whole crate::node_id::get_node_id

2021-09-29 20:15 UTC, agunde406 requested changes

2021-09-29 20:15 UTC, agunde406 commented on splinterd/src/daemon.rs
> +        let node_id = self
This should remain an option here and not be generated if None, that happens in your get_node_id() function that is called in SplinterDaemon.start(). Not this means that it should not be returning an error here.

2021-09-29 20:15 UTC, agunde406 commented on splinterd/src/daemon.rs
> +        let display_name = self
This should also remain an option and use the node id that is created in SplinterDaemon.start() if display name is not set.

2021-10-01 16:31 UTC, agunde406 approved these changes
Tested

2021-10-04 19:51 UTC, peterschwarz approved these changes

2021-10-04 19:52 UTC, merged