Add Release Notes for 0.5.19
Cargill/splinter pull request #1528
Opened 2021-09-23 18:03 UTC by Caleb-Hill

Signed-off-by: Caleb Hill <hill@bitwise.io>

2021-09-23 19:20 UTC, agunde406 requested changes

2021-09-23 19:20 UTC, agunde406 commented on RELEASE_NOTES.md
> +## Changes in Splinter 0.5.18
Remove this section, it is a duplicate.

2021-09-23 19:20 UTC, agunde406 commented on RELEASE_NOTES.md
> +node to know which public key is being used as their identity on the other node
Please update the doc to the formatting is consistent, some sections do not line up with the others.

2021-09-23 19:20 UTC, agunde406 commented on RELEASE_NOTES.md
> +
Remove extra line

2021-09-23 19:20 UTC, agunde406 commented on RELEASE_NOTES.md
> +  be listed separately: ``` Endpoints: tcp://127.0.0.1:18044
The endpoint example is not formatted correctly

2021-09-23 20:37 UTC, agunde406 approved these changes

2021-09-24 13:51 UTC, peterschwarz approved these changes

2021-09-24 17:36 UTC, rbuysse requested changes
s/Simply/Simple

2021-09-24 17:36 UTC, rbuysse commented on RELEASE_NOTES.md
> +* Simply back-pressure has been added to the scabbard `/batches` route. If
s/Simply/Simple

2021-09-24 18:08 UTC, agunde406 approved these changes

2021-09-24 19:21 UTC, peterschwarz approved these changes

2021-09-24 19:24 UTC, agunde406 approved these changes

2021-09-24 20:44 UTC, rbuysse approved these changes

2021-09-24 20:45 UTC, merged