Node id upgrade tests
Cargill/splinter pull request #1532
Opened 2021-09-27 17:01 UTC by Caleb-Hill

Adding tests to import_store function within the database upgrade action.

2021-09-28 21:52 UTC, leebradley approved these changes

2021-09-29 14:32 UTC, leebradley submitted a review, later dismissed

2021-09-29 16:30 UTC, leebradley submitted a review, later dismissed

2021-09-29 16:43 UTC, peterschwarz requested changes

2021-09-29 16:43 UTC, peterschwarz commented on cli/src/action/database/upgrade/node_id.rs
> +#[derive(PartialEq)]
If this is being used in tests, you can also use the `matches!` macro

2021-09-29 16:43 UTC, peterschwarz commented on cli/src/action/database/upgrade/node_id.rs
> +    use crate::action::database::upgrade::node_id::{
Importing from the parent module in tests is one of the few areas where `use super::*` is fine.

2021-09-29 16:43 UTC, peterschwarz commented on cli/src/action/database/upgrade/node_id.rs
> +mod action_tests {
The current convention is to name this `tests`

2021-10-01 15:33 UTC, leebradley approved these changes

2021-10-01 16:37 UTC, merged