Refactor daemon
Cargill/splinter pull request #1542
Opened 2021-10-01 19:24 UTC by Caleb-Hill

daemon.rs had multiple structs/enums and all their associated implementation details in one big file, this splits them out into multiple modules under the same daemon module.

2021-10-04 16:43 UTC, vaporos submitted a review, later dismissed

2021-10-04 16:49 UTC, peterschwarz approved these changes

2021-10-05 13:19 UTC, vaporos submitted a review, later dismissed

2021-10-05 13:43 UTC, agunde406 requested changes

2021-10-05 13:43 UTC, agunde406 commented on splinterd/src/daemon/mod.rs
> +pub mod builder;
By convention modules should be added at the top of the file, before the use statements

2021-10-05 15:02 UTC, agunde406 approved these changes

2021-10-05 15:42 UTC, peterschwarz approved these changes

2021-10-05 15:43 UTC, vaporos approved these changes

2021-10-05 16:46 UTC, merged