Stabilize node-id-upgrade by adding it to stable
Cargill/splinter pull request #1552
Opened 2021-10-05 15:41 UTC by Caleb-Hill

Depends on `libsplinter/node-id-store` and `upgrade` which can still be
compiled out so the feature is still required. This commit adds it to
the cli `stable` feature set.

Signed-off-by: Caleb Hill <hill@bitwise.io>

2021-10-05 15:53 UTC, peterschwarz requested changes
This feature should probably be removed

2021-10-05 18:39 UTC, peterschwarz commented on cli/src/action/database/upgrade/mod.rs
> +        let db_store = store_factory.get_node_id_store();
I think these activities should be guarded by 
```rust
#cfg(any(feature = "postgres", feature = "sqlite"))]
```

2021-10-06 14:28 UTC, peterschwarz submitted a review, later dismissed

2021-10-06 19:50 UTC, peterschwarz approved these changes

2021-10-06 20:05 UTC, leebradley approved these changes

2021-10-06 20:07 UTC, merged