Add openapi lint
Cargill/splinter pull request #1601
Opened 2021-10-22 20:28 UTC by leebradley

2021-11-05 18:45 UTC, rbuysse requested changes

2021-11-08 15:08 UTC, leebradley commented on .github/workflows/lint-openapi.yaml
> +      - name: Notify Slack of Failure
Removed!

2021-11-08 15:09 UTC, leebradley commented on justfile
> +    just ci-lint-openapi
Done

2021-11-08 16:16 UTC, vaporos approved these changes

2021-11-10 21:16 UTC, peterschwarz approved these changes

2021-11-11 16:14 UTC, rbuysse approved these changes

2021-11-11 16:26 UTC, merged