Fix error handling so the error isn't discarded
Cargill/splinter pull request #1604
Opened 2021-10-25 16:38 UTC by Caleb-Hill

The code used to discard the error by converting it to a None value which led to other problems. Now the closure returns an Option<Result<Option<String>,err>> so that the error message lives long enough to be returned by the containing function. 

Signed-off-by: Caleb Hill <hill@bitwise.io>

2021-11-05 19:14 UTC, vaporos requested changes
The resulting code is overly complex to understand with the nested results and options; this comes through in needing to call things like flatten and translate. And even then, it doesn't remove the final unwrap().

The fundamental coding error here is in the existing code - mixing two things that should be separate:

1. Figuring out the path.
2. Creating the directory if we are using SPLINTER_HOME.

A better flow would be:

```
let cert_dir_string = .... // figure out the string (don't create the directory)

let cert_dir = Path::new(&cert_dir_string);

if !cert_dir.is_dir() {
    // here, handle two cases:
    // if we are using SPLINTER_HOME, then try to create the directory
    // otherwise, error out
}
```

2021-11-11 14:56 UTC, Caleb-Hill commented on cli/src/action/certs.rs
> +            Path::new(&splinter_home).join("certs")
fixed

2021-11-11 15:06 UTC, vaporos approved these changes

2021-11-12 14:54 UTC, agunde406 approved these changes

2021-11-12 15:03 UTC, merged