Add assignment endpoints openapi
Cargill/splinter pull request #1735
Opened 2021-12-17 03:17 UTC by Caleb-Hill

Adds authorization/assignments endpoint definitions as well as the supporting structures.

2021-12-20 19:27 UTC, vaporos approved these changes

2021-12-20 19:32 UTC, agunde406 approved these changes

2021-12-20 19:33 UTC, peterschwarz requested changes

2021-12-20 19:33 UTC, peterschwarz commented on splinterd/api/static/openapi.yaml
> +
Looks like an extra blank line

2021-12-20 19:54 UTC, Caleb-Hill commented on splinterd/api/static/openapi.yaml
> +
Fixed

2021-12-22 16:48 UTC, vaporos approved these changes

2021-12-22 18:53 UTC, agunde406 approved these changes

2022-01-03 15:38 UTC, peterschwarz approved these changes

2022-01-03 15:55 UTC, Caleb-Hill commented
Backport PR here https://github.com/Cargill/splinter/pull/1755

2022-01-03 15:55 UTC, merged