Correct foreign key constraint on rbac_assignment
Cargill/splinter pull request #1854
Opened 2022-03-15 18:33 UTC by peterschwarz

This change corrects the foreign key constrait on the rbac_assignment table which was not correctly updated after the table was renamed.

2022-03-15 20:54 UTC, Caleb-Hill submitted a review, later dismissed

2022-03-15 21:43 UTC, agunde406 requested changes
Typo in file name: foriegn -> foreign

2022-03-16 13:55 UTC, peterschwarz commented
Typo fixed

2022-03-16 13:56 UTC, Caleb-Hill approved these changes

2022-03-16 13:56 UTC, agunde406 approved these changes

2022-03-16 14:00 UTC, vaporos approved these changes

2022-03-16 15:17 UTC, merged