Rename Service::peer_id to ::local_peer_id
Cargill/splinter pull request #1864
Opened 2022-03-21 16:51 UTC by peterschwarz

This change renames circuit::routing::Service::peer_id to ::local_peer_id as it is a more accurate name for its purpose (matching its rustdoc comment, for example).

2022-03-21 16:59 UTC, vaporos requested changes
This changes a public API - circuit::routing::Service::peer_id() etc., so minimally a those functions should be retained as wrappers to the new names.

2022-03-21 18:29 UTC, peterschwarz commented
I've restored the original functions and marked them as deprecated.

2022-03-21 18:31 UTC, vaporos submitted a review, later dismissed

2022-03-22 18:24 UTC, agunde406 approved these changes

2022-03-22 18:25 UTC, vaporos approved these changes

2022-03-22 18:26 UTC, merged