Stabilize service-type
Cargill/splinter pull request #1967
Opened 2022-05-16 20:53 UTC by peterschwarz

This change stabilizing the "service-type" feature by removing it.  The code previously guarded by the feature is guarded by the general "service" feature.

2022-05-16 21:17 UTC, vaporos submitted a review, later dismissed

2022-05-17 13:43 UTC, agunde406 requested changes
The "service" feature has not been added yet

2022-05-17 14:33 UTC, vaporos approved these changes

2022-05-17 14:38 UTC, isabeltomb approved these changes

2022-05-17 15:06 UTC, merged