Move orchestrator rest api code
Cargill/splinter pull request #1974
Opened 2022-05-19 17:46 UTC by Caleb-Hill

This PR updates the ServiceOrchestrator code to split out the resource providing parts and from the actual orchestration of services parts. Then it moves those resource providers to the actix-web-1 crate.

2022-05-24 21:21 UTC, agunde406 requested changes

2022-05-24 21:21 UTC, agunde406 commented on rest_api/actix_web_1/Cargo.toml
> -log = { version = "0.4", optional = true }
These features should stay optional, and instead get pulled in if "service" or "admin-service" is pulled in.

2022-05-26 14:14 UTC, agunde406 approved these changes
Tested

2022-05-31 17:10 UTC, vaporos approved these changes

2022-05-31 19:08 UTC, peterschwarz approved these changes

2022-06-01 21:46 UTC, merged