Auto cleanup scabbard pruning
Cargill/splinter pull request #2025
Opened 2022-06-20 22:18 UTC by peterschwarz

This PR enables auto cleanup of pruned scabbard state trees by default, or allows the feature to be disabled by the use of the flag `--disable-scabbard-autocleanup`

2022-06-21 15:37 UTC, vaporos submitted a review, later dismissed

2022-06-22 18:16 UTC, agunde406 requested changes

2022-06-22 18:16 UTC, agunde406 commented on splinterd/packaging/splinterd.toml.example
> +# Enable Auto-cleanup of Scabbard state;o
typeo ";o"

2022-06-22 18:16 UTC, agunde406 commented on services/scabbard/libscabbard/src/service/factory/mod.rs
> +    enable_state_autocleanup: Option<bool>,
typo in commit message: ads -> adds

2022-06-22 18:23 UTC, agunde406 approved these changes

2022-06-22 18:28 UTC, peterschwarz commented on splinterd/packaging/splinterd.toml.example
> +# Enable Auto-cleanup of Scabbard state;o
Fixed

2022-06-22 18:28 UTC, peterschwarz commented on services/scabbard/libscabbard/src/service/factory/mod.rs
> +    enable_state_autocleanup: Option<bool>,
Fixed

2022-06-23 15:23 UTC, vaporos approved these changes

2022-06-23 15:36 UTC, merged